name: taxi-pipeline
schedule: daily
start_date: "2019-01-01"

default_connections:
  duckdb: duckdb-default

# - Variables must have a `default` so assets can render without `--var`.
# - In SQL/YAML assets: reference as `{{ var.my_variable }}`.
# - In Python assets: read JSON from env var `BRUIN_VARS`.
variables:
  taxi_types:
    type: array
    items:
      type: string  
    default: ["yellow"] # default is yellow to use smaller dataset for development
  max_months:
    type: integer
    default: 3
#   other_string_var: (optional) Add your own variable and use it in both Python and SQL assets.
#     type: string
#     default: "my_value"